services:
  andromeda-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: andromeda-app
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: andromeda_db
      POSTGRES_USER: andromeda_user
      POSTGRES_PASSWORD: andromeda_password
      DB_HOST: postgres-db
      DB_PORT: 5432
    depends_on:
      - postgres-db
    networks:
      - andromeda

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - andromeda-app
      - keycloak
    networks:
      - andromeda

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - andromeda

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: andromeda_db
      POSTGRES_USER: andromeda_user
      POSTGRES_PASSWORD: andromeda_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - andromeda

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - andromeda

volumes:
  postgres-data:

networks:
  andromeda:
    driver: bridge
