version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    hostname: postgres_db
    environment:
      POSTGRES_DB: andromeda_db
      POSTGRES_USER: andromeda_user
      POSTGRES_PASSWORD: andromeda_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - andromeda

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: andromeda_db
      DB_USER: andromeda_user
      DB_PASSWORD: andromeda_pass
      KC_HOSTNAME: keycloak.dkrrs.net
    ports:
      - "8080:8080"  # Keycloak web UI port
    depends_on:
      - postgres
    networks:
      - andromeda

  andromeda:
    build:
      context: ./app  # You can keep it the same, or point to a Dockerfile path
    container_name: andromeda
    environment:
      DATABASE_URL: postgresql://andromeda_user:andromeda_pass@postgres:5432/andromeda_db
      FLASK_APP: app.py  # Set the Flask app entry point if required
      FLASK_ENV: production  # Or 'development' for development mode
    volumes:
      - static:/var/andromeda/static/
      - media:/var/andromeda/media/
    depends_on:
      - postgres
    networks:
      - andromeda
    ports:
      - "5000:5000"  # Flask app runs on port 5000 internally
    restart: unless-stopped  # Restart policy to keep the app running

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"    # HTTP traffic
      - "443:443"  # HTTPS traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the Nginx configuration file
      - ./html:/usr/share/nginx/html:ro       # Optional: mount static files directory
      - ./data/certbot/conf:/etc/letsencrypt   # Certbot configuration and certificates
      - ./data/certbot/www:/var/www/certbot   # Certbot challenge directory
      - static:/var/andromeda/static/
      - media:/var/andromeda/media/
    depends_on:
      - andromeda
      - keycloak
    networks:
      - andromeda

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  static:
  media:

networks:
  andromeda:
